### ISSUE TITLE
SVG Sprite Loader compatibility

### ISSUE THREAD

**Issue by oknoorap** [react-icons/react-icons#368]
Please make `react-icons` compatible with https://www.npmjs.com/package/svg-sprite-loader

### Use case
I want to create a star rating system, e.g I have 20 customers and submit rating in our system, each customer submit 5 stars, I don't want to loop MdStar from Material Design Icon, it would be useful if we're not renders `<path />` 100 times, I want to rendering more efficient way by using `<symbol />` and `<use />` tag instead.

### Purpose
To avoid an excessive DOM size in Google Lighthouse
reference: https://web.dev/dom-size/

**Comment by kamijin-fanta** [comment]
In this project, SVG is converted to JSON structure and used. So this loader is not available.

Also, I don't think DOM-Size and svg-sprite-loader are relevant.

**Comment by AdsonCicilioti** [comment]
> In this project, SVG is converted to JSON structure and used. So this loader is not available.
> 
> Also, I don't think DOM-Size and svg-sprite-loader are relevant.

What!?
How so?

**Comment by jurerotar** [comment]
A bit late to this issue, but I'll leave a comment in case anyone else encounters the same problem. 

I've created a small package that generates a sprite sheet from the icons you use. It then automatically replaces all would-be deep and inline <svg> trees with a quick <use> reference. In case you're running in to issues with deeply nested `<svg>` trees, take a look at the package, it will produce a smaller DOM, since you're not adding (potentially) dozens of `<path>` elements to the DOM.

https://github.com/jurerotar/react-icons-sprite

**Comment by oknoorap** [comment]
Excellent work @jurerotar 🫡 wonderful.
