### ISSUE TITLE
Error with react-icons and vercel with Astro

### ISSUE THREAD

**Issue by juanppdev** [react-icons/react-icons#754]
I get this error when deploying to vecel using Astro

 error   Named export 'BsFillCameraFill' not found. The requested module 'react-icons/bs/index.esm.js' is a CommonJS module, which may not support all module.exports as named exports.
12:46:32 PM:   CommonJS modules can always be imported via the default export, for example using:
12:46:32 PM:   import pkg from 'react-icons/bs/index.esm.js';
12:46:32 PM:   const { BsFillCameraFill } = pkg;
12:46:32 PM:

**Comment by saaymeen** [comment]
Hi, I'm running into a similar issue. What was the solution here?

**Comment by hannesuw** [comment]
This can be solved by
Importing the library using the expected way.

` import pkg from 'react-icons/bs/index.esm.js'`
`const { BsFillCameraFill } = pkg`

But the problem is, it throw this error while building

(node:26838) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/johanneswijaya/Documents/projects/hacktiv-alumni/node_modules/.pnpm/react-icons@4.10.1_react@18.0.0/node_modules/react-icons/ai/index.esm.js:2
import { GenIcon } from '../lib';

**Comment by chicoryr** [comment]
Any update on this?
