### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'Provider') in nextjs 13 + pnpm

### ISSUE THREAD

**Issue by jeffng50** [react-icons/react-icons#770]
### Describe the bug

![react-icon](https://github.com/react-icons/react-icons/assets/78723468/37d1b205-94d0-4821-ab7e-bec239651118)

Getting this error when using `<IconContext.Provider`, moved it to my `layout.tsx` but to no avail :(
```
<html lang="en">
      <body className={`${inter.className} bg-base-100`}>
        <IconContext.Provider value={{ size: "3em" }}>
          <Header />
          {children}
          <Footer />
        </IconContext.Provider>
      </body>
    </html>
```

### Expected behavior

Should not be undefined

### Minimal sample repository URL

none

### Steps To Reproduce

1. Nextjs 13
2. using `pnpm dev` which calls `next dev`
3. compile issue as shown in pic 

### Package version

v4.10.1

### Additional context

```
"dependencies": {
    "@types/node": "20.4.0",
    "@types/react": "18.2.14",
    "@types/react-dom": "18.2.6",
    "autoprefixer": "10.4.14",
    "eslint": "8.44.0",
    "eslint-config-next": "13.4.9",
    "next": "13.4.9",
    "postcss": "8.4.25",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.10.1",
    "tailwindcss": "3.3.2",
    "typescript": "5.1.6"
  },
  "devDependencies": {
    "daisyui": "^3.1.11"
  }
```

```
pnpm v8.6.6
node v18.16.1 LTS
Windows 10
```

**Comment by jduran7** [comment]
Have you tried adding "use client" at the beginning of your component file? that did the trick for me.

**Comment by jeffng50** [comment]
@jduran7 that works, thanks!! However I've placed the Provider at the RootLayout, by making that a client component, I think it defeats the purpose of SSR/RSC :((

Are there any better alternatives? I am currently bypassing the issue by not using `IconContext.Provider` and just passing a global size that I want

**Comment by Louis-7** [comment]
@jeffng50  this [post](https://stackoverflow.com/a/76181667/4436090) work for me! You need to wrap react-icon into a client component.

```
// icons.tsx

"use client";

import * as React from "react";
import { IconSvgProps } from "@/types";
import { AiFillTrophy } from "react-icons/ai";

export const Logo: React.FC<IconSvgProps> = ({ size = "1em", ...props }) => (
  <AiFillTrophy size={size} />
);

```

You can still keep the component where uses this icon as SSR component.

**Comment by kiurious** [comment]
You can download the necessary SVG's also instead of loading the library. 
Also, even though `'use client'` renders on the client, NextJS still pre-renders a non-interactive preview of the component on the server and then hydrates it for interactivity on the client. You can read more about it [here](https://nextjs.org/docs/app/building-your-application/rendering/client-components#benefits-of-client-rendering).

**Comment by AndresTeller** [comment]
I was experiencing the same issue, so I decided to create a CustomIcon that makes use of IconType, but without using IconContext.Provider as it causes conflicts.

```jsx
// custom-icon.tsx
import { IconBaseProps } from "react-icons";
import { IconType } from "react-icons";

interface CustomIconProps extends IconBaseProps {
  icon: IconType;
}

export const CustomIcon: React.FC<
  CustomIconProps & React.HTMLProps<SVGElement>
> = ({ icon: Icon, size = 30, ...props }) => <Icon size={size} {...props} />;
```
I added a default size based on my personal preferences, feel free to modify or remove it.

Here you can see a basic usage of it (in my case, I'm using Tailwind CSS, but we can also use the color property):

```tsx
// basic usage
import { FaBeer } from "react-icons/fa";
import { CustomIcon } from "../custom-icon";

const TestPage = () => {
  return (
    <div>
      <h1>My custom icon: </h1>

      <CustomIcon
        icon={FaBeer}
        className="ml-10 text-blue-200"
        size={50}
        title="Some title"
      />
    </div>
  );
}

export default TestPage
```
I use the FaBeer icon since it is the one used in the official documentation for examples.

Finally, here is a visual sample of how the final result turned out:

![image](https://github.com/react-icons/react-icons/assets/105757642/be8b1f4d-855b-43c2-9200-d67280ec8be7)

**Comment by amjedidiah** [comment]
@AndresTeller 
You're doing well

Works fine for me

**Comment by karladler** [comment]
That's kinda not satisfying. Using a wrapper component or client renderer for such a simple thing like svg sizing.
Having a default css class at the icon would make it so much simpler to style it.
