### ISSUE TITLE
[Feature]: Support tree-shaking for next.js

### ISSUE THREAD

**Issue by stx-chris** [react-icons/react-icons#786]
### Describe

Right now Next.js seems unable to properly tree-shake this library. 

### Solution

Is there something that can be done to make sure only specific icons get imported instead of the whole library?

**Comment by breakerh** [comment]
Installing react-icons/all-files (use the github releases because of #593 )
`npm i https://github.com/react-icons/react-icons/releases/download/v4.10.1/react-icons-all-files-4.10.1.tgz`
and add this to your next.config.js
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
    modularizeImports: {
        "react-icons/?(((\\w*)?/?)*)": {
            transform: "@react-icons/all-files/{{ matches.[1] }}/{{ member }}",
            skipDefaultConversion: true
        }
    }
}

module.exports = nextConfig
```

Fixes the slow loading issue..
only negative thing is it takes a long time to install the package.

**Comment by mattvv** [comment]
I had to ignoreBuildErrors from typescript for this to work, anyone have a cleaner way?

**Comment by breakerh** [comment]
> I had to ignoreBuildErrors from typescript for this to work, anyone have a cleaner way?

Didnt see this. But it shouldn't fire any build errors?
